version: '3.9'
services:
  app:
    image: node:16-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    entrypoint: ['/bin/sh', '-c', 'yarn && yarn start:dev']
#    entrypoint: ['tail', '-f', '/dev/null']
  testing:
    image: node:16-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    entrypoint: ['/bin/sh', '-c', 'yarn && yarn test' ]
  postgres:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
    ports:
      - '5432:5432'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
